### PR TITLE
Closes #94

### LINKED ISSUE #94: better-sqlite driver is not supported
See https://github.com/knex/knex/issues/4961

### PR DESCRIPTION
**Pull request by ozziest**
Closes #94

### CODE REVIEW

**Comment by kibertoad** [comment]
Thank you! Can you also add test?

**Comment by ozziest** [comment]
I am not sure how to add tests properly. 

First, I realized that the `knex` version is `^0.95.14` in the package.json file. Should I update it to the latest version? Also, in the latest version, `vscode-sqlite3` package is being looked for. Should I add that package?

**Comment by kibertoad** [comment]
Yes, would be good to add both.

**Comment by kibertoad** [comment]
@ozziest Do you need any help?

**Comment by ozziest** [comment]
@kibertoad , I am sorry but I couldn't find time to work on it. :/ If I am blocking the issue, someone else can work on it because I will not be free this week. If you can give me another week, I would love to contribute it as I can.

**Comment by ozziest** [comment]
Hi @kibertoad ,

I am sorry but I couldn't resolve the issue. Even I updated `knex` version, and add `vscode-sqlite3` to the package.json, when I run tests, I get the following errors;

```
$ npm install sqlite3 --save
Cannot find module '@vscode/sqlite3'
Require stack:
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/node_modules/knex/lib/dialects/sqlite3/index.js
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/node_modules/knex/lib/knex-builder/internal/config-resolver.js
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/node_modules/knex/lib/knex-builder/Knex.js
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/node_modules/knex/lib/index.js
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/node_modules/knex/knex.js
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/test/mysql.spec.ts
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/node_modules/mocha/lib/esm-utils.js
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/node_modules/mocha/lib/mocha.js
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/node_modules/mocha/lib/cli/one-and-dones.js
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/node_modules/mocha/lib/cli/options.js
- /home/ozzy/Desktop/github/ozziest/knex-schema-inspector/node_modules/mocha/bin/mocha
```

Probably I am missing some little point but I think that it can be solved quickly by someone who know the package very well.

**Comment by rijkvanzanten** [comment]
@ozziest I think it's simply because `@vscode/sqlite` isn't installed in this project (yet). A `npm install @vscode/sqlite -D` should do the trick 🙂

**Comment by ozziest** [comment]
> @ozziest I think it's simply because `@vscode/sqlite` isn't installed in this project (yet). A `npm install @vscode/sqlite -D` should do the trick slightly_smiling_face

Unfortunately, I get the same error after I install `vscode/sqlite`. I have no idea why. I really wanted to make some contribution but I don't have enough information about what's going on here. That's why I have to close my PR.

**Pull request closed without merging**
