### PR TITLE
Optimized Oracle queries for performance

### PR DESCRIPTION
**Pull request by aidenfoxx**
Improved the performance of Oracle queries, particularly cold queries. The results from the integration test:

**Old (Cold queries):**
```
    .columnInfo
      ✓ returns information for all columns in all tables (2763ms)
      ✓ returns information for all columns in specific table (2057ms)
      ✓ returns information for a specific column in a specific table (2010ms)
    .foreignKeys
      ✓ returns foreign keys for all tables (498ms)
```

**New (Cold queries):**
```
    .columnInfo
      ✓ returns information for all columns in all tables (1901ms)
      ✓ returns information for all columns in specific table (1736ms)
      ✓ returns information for a specific column in a specific table (1802ms)
    .foreignKeys
      ✓ returns foreign keys for all tables (232ms)
```
There are almost certainly more optimizations that could be made.

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by aidenfoxx** [comment]
Just noticed a potential issue looking at the diff. Will reopen once verified.

**Comment by aidenfoxx** [comment]
I'm just insane... There was no issue. Tested against directus locally and everything seems to be working the same.

**Comment by rijkvanzanten** [comment]
@aidenfoxx The CI is complaining about the code style though. Mind running prettier real quick?

**Comment by aidenfoxx** [comment]
So prettier passes locally, but fails on Github. You ever seen this @rijkvanzanten?

**Comment by rijkvanzanten** [comment]
Odd! Maybe a different version of Prettier with different defaults? I've seen Prettier update rules in minor patches before, so that would explain it 🤔

**Comment by aidenfoxx** [comment]
Well that's dumb. If I `npm ci` then the prettier has different results to if I `yarn install --frozen-lockfile`. 🤦

**Comment by rijkvanzanten** [comment]
Yeah same here ᕕ( ᐛ )ᕗ

**Comment by aidenfoxx** [comment]
I guess yarn just ignores the `package-lock.json` with `--frozen-lockfile` and does it's own thing. You learn something new every day... 🤔

**Pull request merged**
