### PR TITLE
Fix postgres `is_unique` flag generation when part of composed constraint

### PR DESCRIPTION
**Pull request by cah4a**

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
@Oreilles looking good?

**Comment by Oreilles** [comment]
Sure! Now let's do this for all other vendors 😁

**Comment by rijkvanzanten** [comment]
@cah4a Is that something you'd be willing to look into?

**Comment by cah4a** [comment]
@rijkvanzanten Yep, will do. It could take some time, never use oracle or mssql.

**Comment by Oreilles** [comment]
@cah4a Already working on it 👍  SQL Server is done, finding a way for Oracle now.

**Comment by rijkvanzanten** [comment]
Closed in favor of #79, which includes this change. Thanks again @cah4a!

**Pull request closed without merging**
