### PR TITLE
Fixed issue-60 with regex that allows multi-line json

### LINKED ISSUE #60: Multi-line JSON not properly unescaped
Hey, we noticed what we believe is a breaking change introduced in `1.3.0+` versions of `knex-schema-inspector` originating from https://github.com/knex/knex-schema-inspector/commit/b5cdeae8df2647e91cfe570f6be04da8e0e17e0e which refactored `parseDefaultValue`. Previously, it correctly handled multi-line JSON but after the refactor, newlines are not properly matched and multi-line json causes Directus to crash with the following error:

```
17:05:04 🚨 Unexpected token ' in JSON at position 0 
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parseDefaultValue (/Users/glen/Git/divvit/api/node_modules/knex-schema-inspector/dist/dialects/postgres.js:77:21)
    at _loop_1 (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:115:50)
    at Postgres.<anonymous> (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:119:29)
    at step (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:78:23)
    at Object.next (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:59:53)
    at fulfilled (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:50:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The cause for this is related to a refactor of `parseDefaultValue` which changed checks from using `startsWith` and `endsWith` to a regex which doesn't properly handle multi-lines.

BEFORE (worked properly):
```javascript
if (value.startsWith("'") && value.endsWith("'")) {
  value = value.slice(1, -1);
}
```

AFTER https://github.com/knex/knex-schema-inspector/commit/b5cdeae8df2647e91cfe570f6be04da8e0e17e0e:
```javascript
value = value.replace(/^\'(.*)\'$/, '$1');
```

To fix, the regex can be modified to use `\s\S` instead of `.`
```javascript
value = value.replace(/^\'([\s\S]*)\'$/, '$1');
```

We first noticed this issue about a month ago but used older pre-built Docker images where the `knex-schema-inspector` dependency was still `1.2.2`. Directus depends on `knex-schema-inspector` but it is not hard pinned so minors are pulled in. We are fairly certain versions `1.3.0+` have this breaking change.

We found the cause of this issue by printing values from `parseDefaultValue` and the last to print before erroring out was a json value that still had single quotes `'` around it (see below). Running this through `JSON.parse` will of course fail. When we dug into the code and found the regex we noticed this formatted json string (with newlines) never matched properly. More digging and we stumbled on the old code which used `startsWith` and `endsWith` and it all started to make sense.
```
'[
    {
        "amount": "60",
        "label": "Min",
        "value": 6000
    },
    {
        "amount": "75",
        "label": "Average",
        "value": 7500,
        "default": true
    }
]'
17:05:04 🚨 Unexpected token ' in JSON at position 0 
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parseDefaultValue (/Users/glen/Git/divvit/api/node_modules/knex-schema-inspector/dist/dialects/postgres.js:77:21)
    at _loop_1 (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:115:50)
    at Postgres.<anonymous> (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:119:29)
    at step (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:78:23)
    at Object.next (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:59:53)
    at fulfilled (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:50:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### PR DESCRIPTION
**Pull request by glenselle**
Fixes #60 -- I didn't see any test file testing `parseDefaultValue` -- did I miss it?

### CODE REVIEW

**Comment by aidenfoxx** [comment]
It looks like Microsoft might have deleted the docker image used in the tests. Apparently it was depreciated: https://hub.docker.com/r/microsoft/mssql-server-linux

We should probably disable the MSSQL tests for now if that's the case.

**Comment by glenselle** [comment]
There's also this
```
Head https://registry-1.docker.io/v2/microsoft/mssql-server-linux/manifests/latest: unauthorized: incorrect username or password
```

**Comment by aidenfoxx** [comment]
I updated the MSSQL image and it works fine on #62. You're welcome cherry pick the changes into this branch and we can do it all in this PR, or you wait until it's merged. 😄

**Comment by glenselle** [comment]
@aidenfoxx Can you approve? ` First-time contributors need a maintainer to approve running workflows. Learn more.`

**Comment by aidenfoxx** [comment]
I cannot, but I think @rijkvanzanten will be happy to oblige.

**Comment by glenselle** [comment]
Just FYI, I probably won't be able to get to writing new tests for the `parseDefaultValue` stuff too soon b/c I'm pretty limited on extra time right now.

**Comment by rijkvanzanten** [comment]
No problem! Same here.. Lets merge this for now anyways as it LGTM and is a fairly straightforward change 👍🏻

**Review by rijkvanzanten — APPROVED** [review]

**Comment by glenselle** [comment]
Hey @rijkvanzanten we're currently stuck in a weird spot where I updated our Directus from rc59 to rc71. However, the issue we're experiencing is that rc71 is now set to knex-schema-inspector `1.3.0` which has `parseDefaultValue` has a method but directus/schema tries to import/call it as a function. See here: https://github.com/directus/directus/blob/v9.0.0-rc.69/packages/schema/src/dialects/postgres.ts#L1 

Am I missing something or did the rollback from `1.5` to `1.3` means directus/schema needs to call `parseDefaultValue` as a method like it used to in rc68 here: https://github.com/directus/directus/blob/v9.0.0-rc.68/packages/schema/src/dialects/postgres.ts#L1 ??

I think we can revert back to rc68 and we should be fine. But isn't Directus set to `1.3.0` on the latest version? Isn't the function vs method issue still broken on the tip of the latest Directus?

**Comment by rijkvanzanten** [comment]
>  But isn't Directus set to 1.3.0 on the latest version? Isn't the function vs method issue still broken on the tip of the latest Directus?

No, the latest version of Directus (rc.83 at the time of writing) relies on knex-schema-inspector 1.5.7. I haven't heard anything about issues in the schema inspection recently. I would recommend upgrading to rc.83 🙂

**Comment by glenselle** [comment]
@rijkvanzanten Can this fix be shipped as a patch? 🙏  I just updated us to the latest version of directus (rc83) and our directus is still completely dead. Nothing loads. It's this silly JSON error. We tried going into the DB to get rid of newlines and it appears something (maybe Directus?) is formatting the JSON and adding new lines so we're completely dead unless we delete the data 😢 
```
2021-07-06T16:51:19.090462795Z 16:51:19 ✨ request errored GET 500 /extensions/interfaces/index.js 411ms
2021-07-06T16:51:19.174773519Z 16:51:19 🚨 Unexpected token ' in JSON at position 0 
2021-07-06T16:51:19.174801049Z SyntaxError: Unexpected token ' in JSON at position 0
2021-07-06T16:51:19.174805590Z     at JSON.parse (<anonymous>)
2021-07-06T16:51:19.174809720Z     at Object.parseDefaultValue (/node_modules/knex-schema-inspector/dist/dialects/postgres.js:75:21)
2021-07-06T16:51:19.174813339Z     at _loop_1 (/node_modules/@directus/schema/dist/dialects/postgres.js:115:50)
2021-07-06T16:51:19.174816699Z     at Postgres.<anonymous> (/node_modules/@directus/schema/dist/dialects/postgres.js:119:29)
2021-07-06T16:51:19.174821729Z     at step (/node_modules/@directus/schema/dist/dialects/postgres.js:78:23)
2021-07-06T16:51:19.174824840Z     at Object.next (/node_modules/@directus/schema/dist/dialects/postgres.js:59:53)
2021-07-06T16:51:19.174827980Z     at fulfilled (/node_modules/@directus/schema/dist/dialects/postgres.js:50:58)
2021-07-06T16:51:19.174831049Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by aidenfoxx** [comment]
@glenselle The changes still haven't been released for "knex-schema-inspector". Rijk needs to create a release before it'll be upstreamed into your installation.

**Comment by rijkvanzanten** [comment]
Just pushed out the changes as 1.5.9 👍🏻

**Pull request merged**
