### PR TITLE
some MS SQL fixes

### PR DESCRIPTION
**Pull request by gpetrov**
* fixed missing increment field (extra) and its check to be 1
* added onDelete and onUpdate referential rules

### CODE REVIEW

**Comment by kibertoad** [comment]
Thanks! Could you please update tests?

**Comment by rijkvanzanten** [comment]
> added onDelete and onUpdate referential rules

I'm gonna move this to a standalone feature request issue, as we should implement it across vendors 👍🏻

**Comment by rijkvanzanten** [comment]
Oh never mind, I'm not going to do anything as I don't have edit rights to this PR.. Oh well 🤷🏻

**Comment by rijkvanzanten** [comment]
Closed in favor of https://github.com/knex/knex-schema-inspector/pull/32

**Pull request closed without merging**
