### PR TITLE
feat: add is_unique flag for mysql and postgres, partially fixes #20

### LINKED ISSUE #20: Add "is_unique" flag to returns
To show if a column has a unique constraint set

### PR DESCRIPTION
**Pull request by sercanvirlan**
Just for mysql and postgres

Additionally help needed for mssql, oracledb, sqlite

Partially fixes #20

### CODE REVIEW

**Comment by sercanvirlan** [comment]
MSSQL Added

**Review by sercanvirlan — COMMENTED** [review]
@rijkvanzanten we need sqlite.db file in order to complete unit tests.

**Comment by rijkvanzanten** [comment]
It's created automatically when it's missing 👍🏻

**Comment by rijkvanzanten** [comment]
My bad, i thought it was a leftover from a seeded test, but the structure is slightly different from the other DB vendors 👍🏻

**Comment by rijkvanzanten** [comment]
I tried getting Oracle to run, but for the life of me can't get it to work.. @kibertoad do you have any insight? I tried copying over Knex's setup, but that doesn't seem to run (get some vague `ORA-01012: not logged on` error) on my end.

**Review by rijkvanzanten — APPROVED** [review]

**Comment by rijkvanzanten** [comment]
I'll merge this for now, as everything else is looking good 🙂 

We can figure out Oracle testing separately from this

**Pull request merged**
